/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cnk.communication;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-11-11")
public class MapImagesRequest implements org.apache.thrift.TBase<MapImagesRequest, MapImagesRequest._Fields>, java.io.Serializable, Cloneable, Comparable<MapImagesRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapImagesRequest");

  private static final org.apache.thrift.protocol.TField ACQUIRED_LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("acquiredLevel", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MapImagesRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MapImagesRequestTupleSchemeFactory());
  }

  public int acquiredLevel; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACQUIRED_LEVEL((short)1, "acquiredLevel");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACQUIRED_LEVEL
          return ACQUIRED_LEVEL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACQUIREDLEVEL_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.ACQUIRED_LEVEL};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACQUIRED_LEVEL, new org.apache.thrift.meta_data.FieldMetaData("acquiredLevel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapImagesRequest.class, metaDataMap);
  }

  public MapImagesRequest() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapImagesRequest(MapImagesRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    this.acquiredLevel = other.acquiredLevel;
  }

  public MapImagesRequest deepCopy() {
    return new MapImagesRequest(this);
  }

  @Override
  public void clear() {
    setAcquiredLevelIsSet(false);
    this.acquiredLevel = 0;
  }

  public int getAcquiredLevel() {
    return this.acquiredLevel;
  }

  public MapImagesRequest setAcquiredLevel(int acquiredLevel) {
    this.acquiredLevel = acquiredLevel;
    setAcquiredLevelIsSet(true);
    return this;
  }

  public void unsetAcquiredLevel() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACQUIREDLEVEL_ISSET_ID);
  }

  /** Returns true if field acquiredLevel is set (has been assigned a value) and false otherwise */
  public boolean isSetAcquiredLevel() {
    return EncodingUtils.testBit(__isset_bitfield, __ACQUIREDLEVEL_ISSET_ID);
  }

  public void setAcquiredLevelIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACQUIREDLEVEL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ACQUIRED_LEVEL:
      if (value == null) {
        unsetAcquiredLevel();
      } else {
        setAcquiredLevel((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ACQUIRED_LEVEL:
      return getAcquiredLevel();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ACQUIRED_LEVEL:
      return isSetAcquiredLevel();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MapImagesRequest)
      return this.equals((MapImagesRequest)that);
    return false;
  }

  public boolean equals(MapImagesRequest that) {
    if (that == null)
      return false;

    boolean this_present_acquiredLevel = true && this.isSetAcquiredLevel();
    boolean that_present_acquiredLevel = true && that.isSetAcquiredLevel();
    if (this_present_acquiredLevel || that_present_acquiredLevel) {
      if (!(this_present_acquiredLevel && that_present_acquiredLevel))
        return false;
      if (this.acquiredLevel != that.acquiredLevel)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_acquiredLevel = true && (isSetAcquiredLevel());
    list.add(present_acquiredLevel);
    if (present_acquiredLevel)
      list.add(acquiredLevel);

    return list.hashCode();
  }

  @Override
  public int compareTo(MapImagesRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAcquiredLevel()).compareTo(other.isSetAcquiredLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAcquiredLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.acquiredLevel, other.acquiredLevel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MapImagesRequest(");
    boolean first = true;

    if (isSetAcquiredLevel()) {
      sb.append("acquiredLevel:");
      sb.append(this.acquiredLevel);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapImagesRequestStandardSchemeFactory implements SchemeFactory {
    public MapImagesRequestStandardScheme getScheme() {
      return new MapImagesRequestStandardScheme();
    }
  }

  private static class MapImagesRequestStandardScheme extends StandardScheme<MapImagesRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapImagesRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACQUIRED_LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.acquiredLevel = iprot.readI32();
              struct.setAcquiredLevelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapImagesRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetAcquiredLevel()) {
        oprot.writeFieldBegin(ACQUIRED_LEVEL_FIELD_DESC);
        oprot.writeI32(struct.acquiredLevel);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapImagesRequestTupleSchemeFactory implements SchemeFactory {
    public MapImagesRequestTupleScheme getScheme() {
      return new MapImagesRequestTupleScheme();
    }
  }

  private static class MapImagesRequestTupleScheme extends TupleScheme<MapImagesRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapImagesRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAcquiredLevel()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAcquiredLevel()) {
        oprot.writeI32(struct.acquiredLevel);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapImagesRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.acquiredLevel = iprot.readI32();
        struct.setAcquiredLevelIsSet(true);
      }
    }
  }

}

