/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cnk.communication;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-11-11")
public class MapImagesResponse implements org.apache.thrift.TBase<MapImagesResponse, MapImagesResponse._Fields>, java.io.Serializable, Cloneable, Comparable<MapImagesResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapImagesResponse");

  private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField LEVEL_IMAGE_URLS_FIELD_DESC = new org.apache.thrift.protocol.TField("levelImageUrls", org.apache.thrift.protocol.TType.MAP, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MapImagesResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MapImagesResponseTupleSchemeFactory());
  }

  public int version; // required
  public Map<Integer,String> levelImageUrls; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VERSION((short)1, "version"),
    LEVEL_IMAGE_URLS((short)2, "levelImageUrls");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VERSION
          return VERSION;
        case 2: // LEVEL_IMAGE_URLS
          return LEVEL_IMAGE_URLS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERSION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LEVEL_IMAGE_URLS, new org.apache.thrift.meta_data.FieldMetaData("levelImageUrls", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapImagesResponse.class, metaDataMap);
  }

  public MapImagesResponse() {
  }

  public MapImagesResponse(
    int version,
    Map<Integer,String> levelImageUrls)
  {
    this();
    this.version = version;
    setVersionIsSet(true);
    this.levelImageUrls = levelImageUrls;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapImagesResponse(MapImagesResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.version = other.version;
    if (other.isSetLevelImageUrls()) {
      Map<Integer,String> __this__levelImageUrls = new HashMap<Integer,String>(other.levelImageUrls);
      this.levelImageUrls = __this__levelImageUrls;
    }
  }

  public MapImagesResponse deepCopy() {
    return new MapImagesResponse(this);
  }

  @Override
  public void clear() {
    setVersionIsSet(false);
    this.version = 0;
    this.levelImageUrls = null;
  }

  public int getVersion() {
    return this.version;
  }

  public MapImagesResponse setVersion(int version) {
    this.version = version;
    setVersionIsSet(true);
    return this;
  }

  public void unsetVersion() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  /** Returns true if field version is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion() {
    return EncodingUtils.testBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  public void setVersionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VERSION_ISSET_ID, value);
  }

  public int getLevelImageUrlsSize() {
    return (this.levelImageUrls == null) ? 0 : this.levelImageUrls.size();
  }

  public void putToLevelImageUrls(int key, String val) {
    if (this.levelImageUrls == null) {
      this.levelImageUrls = new HashMap<Integer,String>();
    }
    this.levelImageUrls.put(key, val);
  }

  public Map<Integer,String> getLevelImageUrls() {
    return this.levelImageUrls;
  }

  public MapImagesResponse setLevelImageUrls(Map<Integer,String> levelImageUrls) {
    this.levelImageUrls = levelImageUrls;
    return this;
  }

  public void unsetLevelImageUrls() {
    this.levelImageUrls = null;
  }

  /** Returns true if field levelImageUrls is set (has been assigned a value) and false otherwise */
  public boolean isSetLevelImageUrls() {
    return this.levelImageUrls != null;
  }

  public void setLevelImageUrlsIsSet(boolean value) {
    if (!value) {
      this.levelImageUrls = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VERSION:
      if (value == null) {
        unsetVersion();
      } else {
        setVersion((Integer)value);
      }
      break;

    case LEVEL_IMAGE_URLS:
      if (value == null) {
        unsetLevelImageUrls();
      } else {
        setLevelImageUrls((Map<Integer,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VERSION:
      return getVersion();

    case LEVEL_IMAGE_URLS:
      return getLevelImageUrls();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VERSION:
      return isSetVersion();
    case LEVEL_IMAGE_URLS:
      return isSetLevelImageUrls();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MapImagesResponse)
      return this.equals((MapImagesResponse)that);
    return false;
  }

  public boolean equals(MapImagesResponse that) {
    if (that == null)
      return false;

    boolean this_present_version = true;
    boolean that_present_version = true;
    if (this_present_version || that_present_version) {
      if (!(this_present_version && that_present_version))
        return false;
      if (this.version != that.version)
        return false;
    }

    boolean this_present_levelImageUrls = true && this.isSetLevelImageUrls();
    boolean that_present_levelImageUrls = true && that.isSetLevelImageUrls();
    if (this_present_levelImageUrls || that_present_levelImageUrls) {
      if (!(this_present_levelImageUrls && that_present_levelImageUrls))
        return false;
      if (!this.levelImageUrls.equals(that.levelImageUrls))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_version = true;
    list.add(present_version);
    if (present_version)
      list.add(version);

    boolean present_levelImageUrls = true && (isSetLevelImageUrls());
    list.add(present_levelImageUrls);
    if (present_levelImageUrls)
      list.add(levelImageUrls);

    return list.hashCode();
  }

  @Override
  public int compareTo(MapImagesResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVersion()).compareTo(other.isSetVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLevelImageUrls()).compareTo(other.isSetLevelImageUrls());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLevelImageUrls()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.levelImageUrls, other.levelImageUrls);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MapImagesResponse(");
    boolean first = true;

    sb.append("version:");
    sb.append(this.version);
    first = false;
    if (!first) sb.append(", ");
    sb.append("levelImageUrls:");
    if (this.levelImageUrls == null) {
      sb.append("null");
    } else {
      sb.append(this.levelImageUrls);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapImagesResponseStandardSchemeFactory implements SchemeFactory {
    public MapImagesResponseStandardScheme getScheme() {
      return new MapImagesResponseStandardScheme();
    }
  }

  private static class MapImagesResponseStandardScheme extends StandardScheme<MapImagesResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapImagesResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.version = iprot.readI32();
              struct.setVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LEVEL_IMAGE_URLS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.levelImageUrls = new HashMap<Integer,String>(2*_map0.size);
                int _key1;
                String _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readI32();
                  _val2 = iprot.readString();
                  struct.levelImageUrls.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setLevelImageUrlsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapImagesResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VERSION_FIELD_DESC);
      oprot.writeI32(struct.version);
      oprot.writeFieldEnd();
      if (struct.levelImageUrls != null) {
        oprot.writeFieldBegin(LEVEL_IMAGE_URLS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRING, struct.levelImageUrls.size()));
          for (Map.Entry<Integer, String> _iter4 : struct.levelImageUrls.entrySet())
          {
            oprot.writeI32(_iter4.getKey());
            oprot.writeString(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapImagesResponseTupleSchemeFactory implements SchemeFactory {
    public MapImagesResponseTupleScheme getScheme() {
      return new MapImagesResponseTupleScheme();
    }
  }

  private static class MapImagesResponseTupleScheme extends TupleScheme<MapImagesResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapImagesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVersion()) {
        optionals.set(0);
      }
      if (struct.isSetLevelImageUrls()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVersion()) {
        oprot.writeI32(struct.version);
      }
      if (struct.isSetLevelImageUrls()) {
        {
          oprot.writeI32(struct.levelImageUrls.size());
          for (Map.Entry<Integer, String> _iter5 : struct.levelImageUrls.entrySet())
          {
            oprot.writeI32(_iter5.getKey());
            oprot.writeString(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapImagesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.version = iprot.readI32();
        struct.setVersionIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.levelImageUrls = new HashMap<Integer,String>(2*_map6.size);
          int _key7;
          String _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = iprot.readI32();
            _val8 = iprot.readString();
            struct.levelImageUrls.put(_key7, _val8);
          }
        }
        struct.setLevelImageUrlsIsSet(true);
      }
    }
  }

}

