/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "structs_constants.h"

namespace communication {

const structsConstants g_structs_constants;

structsConstants::structsConstants() {
}

} // namespace

