/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef structs_CONSTANTS_H
#define structs_CONSTANTS_H

#include "structs_types.h"

namespace communication {

class structsConstants {
 public:
  structsConstants();

};

extern const structsConstants g_structs_constants;

} // namespace

#endif
